### PR TITLE
Replaced "Make a Commit" to "What did you do today"

### LINKED ISSUE #33: Replace "Make a commit" with "What did you do today"

### PR DESCRIPTION
**Pull request by ANURAGSISODIYAA**
fixes #33

### CODE REVIEW

**Review by Hojagulyyev — APPROVED** [review]

**Comment by Hojagulyyev** [comment]
this will make commits more readable

**Comment by ANURAGSISODIYAA** [comment]
Thanks , As a bigneer in Open Source. I will read it and will improve my commit messages.

**Comment by Hojagulyyev** [comment]
good luck with your improvements!
can you ask one question, how did you find this repository? I just released this repository yesterday

**Comment by ANURAGSISODIYAA** [comment]
Thank you !😊
I stumbled upon your repository yesterday while actively searching for good first issues on the website https://goodfirstissues.com/ . Your project caught my eye, and I'm excited to contribute.

**Comment by Hojagulyyev** [comment]
@ANURAGSISODIYAA if you are interested in open source projects, you can help me promote rp2 through stars 🌟 and friends 👥️.

I have added a demo link in the Readme.md file, check out the demo, it's fun as a game 🎮, even you can write your own requirement features 🚀 for your team if you want. I think this is great practice for you!

Best regards Hojagulyyev

**Comment by ANURAGSISODIYAA** [comment]
Hi @Hojagulyyev,

Thank you for reaching out! I'm excited to contribute to rp2 and help promote it. I'll definitely check out the demo and explore the features to get a better understanding. If I have any questions or ideas for new features, I'll make sure to share them. Looking forward to being a part of this project!

Best regards, @ANURAGSISODIYAA

**Pull request merged**
